### ISSUE TITLE
Throws "uninitialized constant UIDevice" when run in an OS X app

### ISSUE THREAD

**Issue by senorprogrammer** [jamonholmgren/motion-docs#1]
1. Create a new OS X RubyMotion app.
2. Open the REPL.
3. docs "NSMenuItem"
4. "uninitialized constant UIDevice" and crash

**Comment by jamonholmgren** [comment]
Thanks for the issue @senorprogrammer  --- will check it out next week! Would love a PR if you figure out a good way to deal with this. I don't want it running in production, so maybe we ditch the idea of checking "is this a simulator" and just make sure it's not running in release mode?

**Comment by senorprogrammer** [comment]
I haven't tried this yet but looks like perhaps the RUBYMOTION_ENV var might do it? If it returns "development" then load? I'll give that a try this evening.

**Comment by jamonholmgren** [comment]
Yeah, that would do it. I was trying to be clever with the simulator detection. We may still want to do the sim detection, since if you run `rake mode=release` on an iOS app it'll fire up the sim but `RUBYMOTION_ENV == "release"`. But do it in a more clever way to avoid the UIDevice error.

**Comment by pixlwave** [comment]
Is it possible to simply use rake, and tell it to only add the gem's source when running `build:simulator` and not `build:device`?

**Comment by jamonholmgren** [comment]
We'll still need to access it when running an OSX app, which is not on a simulator.

**Comment by pixlwave** [comment]
I'm still really new at the whole Rake thing, but how about something like:

``` ruby
# OS X Docs
Motion::Project::App.setup do |app|
  if app.template == 'osx'
    app.development do
      app.files << docs_source
    end
  end
end

# iOS Docs
desc "Adds docs"
task :docs do
  App.config.files << docs_source
end

namespace :build do
  desc "Adds docs"
  task :simulator => :docs
end
```

**Comment by jamonholmgren** [comment]
That looks pretty good -- try it with a local copy of MotionDocs and see if it works. :)

**Comment by pixlwave** [comment]
Ok, so I've done this here https://github.com/digitalfx/motion-docs/commit/04d2d246c46698e9ed3740d5940f435bdb0fa585 and it works. However, calling `docs` on all the OS X classes I've tried has resulted in `No Documentation for 'Class Name'`

**Comment by jamonholmgren** [comment]
Ah, dang. There's no documentation available on those APIs, apparently. I'll file a RubyMotion support ticket.

**Comment by jamonholmgren** [comment]
No documentation for iOS anymore. :-/
